### ISSUE TITLE
Compatibility with rust-analyzer

### ISSUE THREAD

**Issue by sergey-tihon** [Juici/int-enum-rs#4]
I there a chance that `IntEnum` can be implemented without expanding to a constant?

> The crate should instead either not emit a constant at all for this, or give the constant the blank name _, which we somewhat support.

Full description - https://github.com/rust-lang/rust-analyzer/issues/13347#issuecomment-1268091704

**Comment by Juici** [comment]
Yeah, the crate is well overdue an update to modern syntax.

**Comment by sergey-tihon** [comment]
This package is used in [Execism exercise](https://exercism.org/tracks/rust/exercises/resistor-color) that teches `External crates` concept. Here is [starting project](https://github.com/exercism/rust/blob/d0dcbcc22e963096d9eda910640070cef16e3697/exercises/concept/resistor-color/Cargo.toml#L7)

It is an unpleasant experience when people learn rust enums and how to work with them using external packages and IDE does not show suggestions.

**Comment by Juici** [comment]
I'm working on a cleanup of the code and a fix.

**Comment by sergey-tihon** [comment]
Thank you @Juici !
